#!/bin/bash
# Regenerates topic_master_data.sql from the local (Mac) copy of SConsole's
# sconsolenxt.topic_master. Refresh the local sconsolenxt first if topics
# have been added in SConsole.
#
# Apply the generated file to a JoveNotes database with:
#   mysql -u root jove_notes < topic_master_data.sql

OUT="$(dirname "$0")/topic_master_data.sql"

{
  echo "-- Generated by gen_topic_master_data.sh on $(date '+%Y-%m-%d %H:%M')"
  echo "-- Source: sconsolenxt.topic_master. Do not edit by hand."
  echo
  echo "DELETE FROM jove_notes.topic_master ;"
  echo
  MYSQL_PWD="$DB_PASSWORD" mysql -u root -N -B sconsolenxt -e "
    SELECT CONCAT( 'INSERT INTO jove_notes.topic_master VALUES ( ',
                   id, ', ', QUOTE(syllabus_name), ', ', QUOTE(section), ', ',
                   QUOTE(topic_name), ' ) ;' )
    FROM topic_master
    ORDER BY id"
} > "$OUT" || exit 1

echo "Wrote $(grep -c '^INSERT' "$OUT") topics to $OUT"
